criterions:
  - name: focal_loss
    target_key: masks
    output_key: pred_masks
    weight: 20
    loss:
      _target_: model_training.loss.FocalLoss
      reduction: none

  - name: iou_loss
    target_key: masks
    output_key: pred_masks
    weight: 1.0
    loss:
      _target_: model_training.loss.IoULoss
      smooth: 1e-6
      reduction: none

  - name: mse_ious_loss
    target_key: gt_ious
    output_key: pred_iou
    weight: 0.05
    loss:
      _target_: torch.nn.MSELoss

full_mask_lambda: 0.1
decay_rate: 0.2
