datasets:
  - ${data_dir}/data/Train_Dataset/DUTS-TR
  - ${data_dir}/data/Train_Dataset/HRSOD-TR
  - ${data_dir}/data/Train_Dataset/UHRSD-TR
train_batch_size: 4
val_batch_size: 4
num_workers: 8
image_size: 1024
val_split: 0.1
transform_mode: regular
test_datasets:
  - "HRSOD-TE"
  - "UHRSD-TE"
  - "DIS-TE1"
  - "DIS-TE2"
  - "DIS-TE3"
  - "DIS-TE4"
  - "DIS-VD"
  - "DAVIS-S"
  - "DUTS-TE"
  - "ECSSD"
  - "HKU-IS"
  - "DUT-OMRON"