_target_: model_training.model.FluxDPTSegmentation
num_classes: 1
num_outputs: 1
encoder_name: "facebook/dinov3-vitl16-pretrain-lvd1689m"
flux_feature_dims: [768, 768, 768, 768]
use_concept_maps: true
use_flux_features: true
use_dino_features: false