# @package _global_

hydra:
  run:
    dir: ./experiments/train_teacher/${now:%Y-%m-%d-%H-%M-%S}

base_dir: "path/to/project"
data_dir: "path/to/datasets"

defaults:
  - backend: 1gpu
  - dataset: full
  - loss: focal_iou
  - model: flux_teacher
  - optimizer: adamw
  - scheduler: cosine
  - train_stage: dev_train
